#!/bin/bash

# Some magic to compile mongoose along with the proxy:
gcc -c -std=c99 deps/mongoose-6.1/mongoose.c -o dist/mongoose.o
g++ -c -std=c++0x source/*.cpp -o dist/proxy-raw.o
g++ -o dist/proxy dist/mongoose.o dist/proxy-raw.o
