#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HTTP_SERVER_DIRNAME="mongoose-6.1"
HTTP_SERVER_FILENAME="mongoose-6.1.zip"

# Init
# if [ "$(whoami)" != "root" ]; then
# 	echo "Root access is required."
# 	exit 1
# fi
cd $CWD

# Prepare dependencies dir
if [ -d "$CWD/deps" ]; then
	rm -rf "$CWD/deps"
fi
mkdir "$CWD/deps"

# Install http server source code
unzip "$CWD/resources/$HTTP_SERVER_FILENAME" -d "$CWD/deps"


# Finish
echo ""
echo "Finished."
